# Generated by Django 2.2 on 2020-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='affected',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covid',
            name='cured',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covid',
            name='death',
            field=models.IntegerField(),
        ),
    ]
