# Generated by Django 2.2 on 2020-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_auto_20200405_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='affected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='cured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='states',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
