# Generated by Django 2.2 on 2020-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_auto_20200405_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='affected',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='cured',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='death',
            field=models.IntegerField(null=True),
        ),
    ]
